# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

repos:
  CRAN: https://cloud.r-project.org
  datacleaning: http://data-cleaning.github.io/drat

after_success:
  - Rscript -e 'covr::codecov()'